@access_token = 
@refresh_token = 
@client_id = 
@client_secret = 
@device_id = 
@scope = read_station

####
# Get measurement
GET https://api.netatmo.com/api/getmeasure
?device_id={{device_id}}
&scale=30min
&type=temperature&optimize=false
&real_time=false
accept: application/json
Authorization: Bearer {{access_token}}

####
#Authorize
POST https://api.netatmo.com/oauth2/authorize
    ?client_id={{client_id}}
    &redirect_uri=https://localhost:8080
    &scope={{scope}}
    &state=myNonce

####
#Get Access and Refresh Tokens
POST https://api.netatmo.com/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

grant_type=authorization_code
&client_id={{client_id}}
&client_secret={{client_secret}}
&code=c7063b0c41c169233561b58d13b7907a
&redirect_uri=https://localhost:8080
&scope=read_station

####
# Refresh Access Token
POST https://api.netatmo.com/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

grant_type=refresh_token
&refresh_token={{refresh_token}}
&client_id={{client_id}}
&client_secret={{client_secret}}
####
